apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: course-nfs-storage
provisioner: fuseim.pri/ifs
reclaimPolicy: Retain  #Retain #Recycle #Delete
#StorageClass default is Delete Policy
